# -*- coding: utf-8 -*-
"""Basic Chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m6yWu_5tdT3MIvVEB9bVfI9OkQI_mbYA
"""

import nltk
from nltk.chat.util import Chat, reflections

# Define patterns for the chatbot
patterns = [
    (r'hi|hello|hey', ['Hello!', 'Hey there!', 'Hi!']),
    (r'how are you?', ['I am doing well, thank you!', 'I\'m good, how about you?']),
    (r'(.*) your name?', ['My name is ChatBot.', 'You can call me ChatBot.']),
    (r'quit', ['Bye! Take care.', 'Goodbye!']),
    # Add more patterns and responses here
]

# Create a chatbot with the defined patterns
chatbot = Chat(patterns, reflections)

def run_chatbot():
    print("Hello! I'm ChatBot. How can I assist you today?")
    while True:
        user_input = input("You: ")
        response = chatbot.respond(user_input)
        print("ChatBot:", response)
        if user_input.lower() == 'quit':
            break

if __name__ == "__main__":
    nltk.download('punkt')
    run_chatbot()